Repository developer-student-club-thapar/algo-book, pull requests merged in 2020-10, with the labels that each got.

#48 Added the C++ code of selection Sort to the algorithms folder
  algorithms/selection_sort/selectionSort.cpp
Labels: hacktoberfest

#51 added python code for selection sort
  algorithms/selection_sort/selection_sort.py
Labels: hacktoberfest

#82 Binary Search
  algorithms/Binary_Search/binary_search.cpp
  algorithms/Binary_Search/binary_search.java
  algorithms/Binary_Search/binary_search.md
  algorithms/Binary_Search/binary_search.py
Labels: hacktoberfest

#70 armstrong.js added
  algorithms/Armstrong Number/Armstrong2.js
Labels: enhancement

#122 docs: modified README
  README.md
Labels: bug, frontend

#119 Implemented a new algorithm(Shell Sort) with Documentation.
  .gitignore
  algorithms/Shell_Sort/Shell_Sort_Readme.md
  algorithms/Shell_Sort/images/This-final-step (img 4).png
  algorithms/Shell_Sort/images/array-of-10-elements (img 1).png
  algorithms/Shell_Sort/images/sorted-sub-lists-and-the-resultant-list (img 3).png
  algorithms/Shell_Sort/images/sub-lists (img 2).png
  algorithms/Shell_Sort/shellSort.cpp
Labels: algo, enhancement, good first issue, question

#80 Added Palindrome
  algorithms/Palindrome/ALGO_README_TEMPLATE.md.txt
  algorithms/Palindrome/Palindrome.cpp
  algorithms/Palindrome/Palindrome.java
  algorithms/Palindrome/Palindrome.js
  algorithms/Palindrome/index.html
Labels: algo, documentation, good first issue
